version: '3.3'
services:
  db:
    image: brainfog_mysql_db 
    container_name: brainfog_mysql_db
    build:
      context: .
      dockerfile: MysqlDB.Dockerfile
    ports:
      - 3306:3306
    environment: 
        MYSQL_DATABASE: brainfog_db
        MYSQL_USER: mysql
        MYSQL_PASSWORD: mysql
        MYSQL_ROOT_PASSWORD: supersecret  
    volumes:
      - brainfog_mysql_db_volume:/var/lib/mysql
  rest:
    image: springboot-brainfog
    container_name: springboot-brainfog
    build:
      context: .
      dockerfile: SpringBootBrainfog.Dockerfile
    ports:
      - 8080:8080
    environment:
      MYSQL_HOST: db      
    depends_on:
      - db
  ui:
    image: angular-brainfog
    container_name: angular-brainfog
    build:
      context: .
      dockerfile: AngularBrainfog.Dockerfile
    ports:
      - 80:80
    depends_on:
      - rest         

volumes:
  brainfog_mysql_db_volume:
