version: '3.3'
services:
  db:
    image: brainfog_mysql_db 
    container_name: brainfog_mysql_db
    build:
      context: .
      dockerfile: MysqlDB.Dockerfile
    ports:
      - 3306:3306
    environment: 
        MYSQL_DATABASE: ${BRAINFOG_MYSQL_DATABASE}
        MYSQL_USER: ${BRAINFOG_MYSQL_USER}
        MYSQL_PASSWORD: ${BRAINFOG_MYSQL_USER_PASSWORD}
        MYSQL_ROOT_PASSWORD: ${BRAINFOG_MYSQL_ROOT_PASSWORD}  
    volumes:
      - brainfog_mysql_db_volume:/var/lib/mysql
  rest:
    image: springboot-brainfog
    container_name: springboot-brainfog
    build:
      context: .
      dockerfile: SpringBootBrainfog.Dockerfile
    ports:
      - 8080:8080
    environment:
      MYSQL_HOST: db 
      BRAINFOG_MYSQL_DATABASE: ${BRAINFOG_MYSQL_DATABASE}
      BRAINFOG_MYSQL_USER: ${BRAINFOG_MYSQL_USER}
      BRAINFOG_MYSQL_USER_PASSWORD: ${BRAINFOG_MYSQL_USER_PASSWORD}
      BRAINFOG_REST_NASA_PLANETARY_APOD_TOKEN: ${BRAINFOG_REST_NASA_PLANETARY_APOD_TOKEN}         
    depends_on:
      - db
  ui:
    image: angular-brainfog
    container_name: angular-brainfog
    build:
      context: .
      dockerfile: AngularBrainfog.Dockerfile
    ports:
      - 80:80
    depends_on:
      - rest         

volumes:
  brainfog_mysql_db_volume:
