-- build here the initial version of the db.
-- flyway requires this file, even if it's empty
--example
--CREATE TABLE PERSON (
--	id BIGINT GENERATED BY DEFAULT AS IDENTITY,
--	first_name varchar(255) not null,
--	last_name varchar(255) not null
--);

